// ARMING — what this system is permitted to do, stated in one place.
//
// TWO DIFFERENT THINGS, DELIBERATELY NOT ONE FLAG. "Armed" here means Telegram may send a human a
// message. It has never meant, and cannot mean, that anything gets placed: there is no Kalshi write
// call anywhere in this build, so trading is not disabled by a setting that could be flipped — it is
// absent. A single `ARMED` boolean covering both would be exactly the over-generalisation this
// project has spent every phase removing.
//
// The two prerequisites below were set by the human and are checked at RUNTIME, not remembered:
// flipping ALERTS_ARMED without them is refused by the runner, so the flag cannot get ahead of the
// evidence.
require("./env");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

const ARMING = {
  // Telegram MAY send. Manual instructions only — the human reads and types.
  ALERTS_ARMED: true,
  armedAt: "2026-07-17",
  armedBy: "explicit human instruction, after both prerequisites were met",
  permits: [
    "Telegram buy instructions for positions the research gates already ruled ACTIONABLE EXPERIMENTAL",
    "Telegram HUMAN REVIEW alerts for unverified news (withdrawal / injury / cancellation)",
    "Telegram price updates, withdrawals, status changes, daily summaries, pipeline failures",
  ],

  // Not a setting. There is no code path to flip.
  TRADING_ENABLED: false,
  tradingNote: "There is no Kalshi write call in this build. Trading is not disabled — it does not exist. `false` here is documentation, not a switch: setting it true would change nothing because nothing reads it to place an order.",

  prerequisites: {
    smallOrderFeeTickets: "authenticated $2 and $5 unsubmitted Quick Order tickets at 0.59 reproduce exactly (3.28 -> $0.06, 8.23 -> $0.14); envelope floor now 3.28 contracts",
    freshFullPipelineRun: "data/attestation.json — machine-generated by run-attest.js, bound to the sealed forecast hash and the active card; expires; production also requires SHARP_PRODUCTION=1",
  },

  standingWarning:
    "This system has NOT demonstrated a predictive edge. The only evaluation that ever showed one is void (contaminated baseline). Every alert carries this.",
};

// How stale an attestation may be before it stops being evidence about the run in front of you. A card
// is scanned, sealed and alerted inside a day; anything older describes a pipeline that has since been
// re-run. Not a tuning knob — a staleness bound.
const FRESH_RUN_MAX_AGE_H = 36;

// The prerequisites, re-checked every run rather than trusted. An armed flag whose evidence has gone
// missing is worse than a disarmed one: it looks like a decision that was made.
//
// `cardId` is REQUIRED. It used to be absent, and that was the whole bug: this function authorised
// money instructions on the strength of data/phase9-fresh-run.json without ever asking which card the
// attestation was about. The file on disk says "13 bouts / 47 claims" about UFC-2026-07-18; the sealed
// artifacts for that same card say 12 and 38. It describes a pipeline run that no longer exists, and it
// returned ok:true anyway — for any card, forever, because `passed` is a boolean a human typed and no
// script has ever written. Absence of a card check is not a smaller version of this bug; it IS the bug.
// PRODUCTION SENDS — the explicit, separate, review-gated setting.
//
// Deliberately read from the ENVIRONMENT, not from committed code. ALERTS_ARMED says the alert path is
// wired; the attestation says a fresh pipeline ran on this card; neither is a decision to send money
// instructions to a phone. That decision is `SHARP_PRODUCTION=1`, and it lives outside the repo on
// purpose: a generator can write an attestation and a commit can flip a boolean, but only a human
// setting an env var in the runtime — after review — can turn on production. Generating the attestation
// cannot arm the system, because the attestation and this switch have nothing to do with each other.
function productionEnabled() {
  return process.env.SHARP_PRODUCTION === "1";
}

// `forecastHash` is optional but, when supplied, BINDING: the attestation must describe the exact
// sealed forecast being alerted, not merely the same card. Two runs of one card produce two seal
// hashes; an attestation about the earlier one is not evidence about the later.
function checkArmingPrerequisites(cardId, forecastHash) {
  const blockers = [];

  const fee = (() => { try { return JSON.parse(fs.readFileSync(path.join(ROOT, "data", "fee-examples.json"), "utf8")); } catch { return []; } })();
  const small = fee.filter((e) => e.totalCost >= 2 && e.totalCost <= 5 && e.treatment === "taker");
  if (!small.length) blockers.push("no authenticated $2-$5 Quick Order fee example — an entertainment order's fee would be extrapolated");

  // A caller that cannot say which card it is alerting cannot be told the attestation matches.
  if (!cardId) blockers.push("checkArmingPrerequisites was called without a cardId — an attestation cannot be matched to an unnamed card");

  const fresh = (() => { try { return JSON.parse(fs.readFileSync(path.join(ROOT, "data", "attestation.json"), "utf8")); } catch { return null; } })();
  if (!fresh) {
    blockers.push("data/attestation.json is missing or unreadable — no machine attestation of a fresh full-pipeline run exists");
  } else {
    if (!fresh.passed) blockers.push(`the attested full-pipeline run did not pass${fresh.failures && fresh.failures.length ? ` (${fresh.failures.join("; ")})` : ""}`);
    // The check that was missing.
    if (cardId && fresh.card !== cardId) {
      blockers.push(`the attestation is for ${fresh.card || "an unnamed card"}, but this run is alerting ${cardId} — an attestation about another card is not evidence about this one`);
    }
    // Bind to the exact sealed forecast, not just the card.
    if (forecastHash && fresh.forecastSealHash && fresh.forecastSealHash !== forecastHash) {
      blockers.push(`the attestation describes forecast ${fresh.forecastSealHash}, but this run is alerting ${forecastHash} — a different sealed run of the same card`);
    }
    if (forecastHash && !fresh.forecastSealHash) {
      blockers.push("the attestation carries no forecastSealHash — it cannot be bound to the sealed forecast being alerted");
    }
    // A timestamp we did not invent: absence is a refusal, not a pass.
    const ranAt = Date.parse(fresh.ranAt || "");
    if (!Number.isFinite(ranAt)) {
      blockers.push("the attestation has no readable ranAt — its age cannot be established, so it cannot be trusted");
    } else {
      const ageH = (Date.now() - ranAt) / 3600000;
      if (ageH > FRESH_RUN_MAX_AGE_H) blockers.push(`the attestation is ${ageH.toFixed(1)}h old (limit ${FRESH_RUN_MAX_AGE_H}h) — it describes an earlier pipeline`);
      if (ageH < -0.5) blockers.push("the attestation is dated in the future — refusing rather than reasoning about a fabricated timestamp");
    }
    // The attestation carries its own expiry; honour it if present (it is stricter than our age bound).
    const exp = Date.parse(fresh.expiresAt || "");
    if (Number.isFinite(exp) && Date.now() > exp) blockers.push(`the attestation expired at ${fresh.expiresAt}`);
    // Machine provenance. A hand-authored file has no writtenBy; the generator stamps one.
    if (!fresh.writtenBy) {
      blockers.push("the attestation has no writtenBy — it is hand-authored, so nothing binds it to the artifacts it describes; run-attest.js must produce it");
    }
  }

  return { ok: blockers.length === 0, blockers, smallOrderTickets: small.length, cardId: cardId || null, forecastHash: forecastHash || null };
}

// A hard structural assertion: if anything ever adds an order path, this trips rather than trades.
//
// This used to be a deny-list of five function names, which proved only that nothing was *called*
// createOrder. It could not see its own case: lib/kalshi.js exports a generic `request(method, path,
// {body, auth})` that signs and POSTs, so an order could be placed through it while this returned true.
// Allowlist the export surface instead — any new export, whatever it is named, trips this — and rely on
// lib/kalshi.js's own transport-level refusal of non-GET methods for the generic hole.
const KALSHI_READ_SURFACE = [
  "request", "get", "getAll",
  "status", "events", "eventsAll", "markets", "marketsAll", "market", "eventDetail", "candlesticks",
  "settlement", "orderbook", "impliedYes", "bestBid", "loadAuth",
];

function assertNoTradingPath() {
  const k = require("./kalshi");
  const actual = Object.keys(k).sort();
  const allowed = [...KALSHI_READ_SURFACE].sort();
  const added = actual.filter((n) => !allowed.includes(n));
  if (added.length) {
    throw new Error(
      `lib/kalshi.js exports ${added.join(", ")}, which is not on the read-only allowlist — ` +
      `this build must not be able to place orders. If this is a legitimate read, add it to KALSHI_READ_SURFACE deliberately.`
    );
  }
  // The generic transport must refuse writes. Prove it here rather than trusting that it still does:
  // a guard that never observes its own failure mode is the bug this repo keeps re-finding.
  let refused = false;
  try { k.request("POST", "/portfolio/orders", { body: {} }); } catch (e) { refused = /read-only|refused/i.test(e.message); }
  if (!refused) throw new Error("lib/kalshi.js request() did not refuse a POST — the read-only transport floor is gone");
  return true;
}

module.exports = { ARMING, checkArmingPrerequisites, assertNoTradingPath, productionEnabled, FRESH_RUN_MAX_AGE_H };
